config/routes.rb
Rails.application.routes.draw do

  root to: 'frontend#index'

  get "services/software-development", to: "frontend#software_development", as: "software_development"
  get "services/web-design", to: "frontend#web_design", as: "web_design"
  get "about", to: "frontend#about", as: "about"

  get "portfolio/:category", to: "frontend#show_portfolio", as: "show_portfolio"
  get "downloads/:category", to: "frontend#show_downloads", as: "show_downloads"
  get "portfolio/:category/:id", to: "frontend#show_attachment", as: "show_portfolio_attachment"
  get "downloads/:category/:id", to: "frontend#show_attachment", as: "show_downloads_attachment"

  mount InyxContactUsRails::Engine, :at => '', as: 'messages'
  mount InyxCatalogRails::Engine, :at => '', as: 'catalog'
  mount InyxBlogRails::Engine, :at => '', as: 'post'
  
  devise_for :users, skip: [:registration]

  resources :admin, only: [:index]

  scope :admin do
  	resources :users do
  		collection do
	  		post '/delete', to: 'users#delete'
  		end
  	end
  end
end

app/views/inyx_blog_rails/categories/_form.html.haml
= simple_form_for(@category) do |f|
  .container_form 
    .title_form
      Datos de categoría
    .form-p
      .input#name{ class: "#{@category.name.blank? ? 'input-false' : 'input-great' }"}
        = f.input :name, input_html: { class: "input_form", id: "input-name",  "ng-focus" => "inputFocus('name')", "ng-blur" => "inputBlur('name')" }
        %br/
      = f.simple_fields_for :subcategories do |c|
        = render 'subcategory_fields', :f => c
      .links
        = link_to_add_association 'añadir subcategoría', f, :subcategories, class: "btn btn-default btn-sm pull-right"
        .clearfix
    .panel-footer
      = f.submit 'Guardar', class: "btn btn-warning pull-right"
      .clearfix

app/views/inyx_blog_rails/categories/_subcategory_fields.html.haml
.nested-fields
	.input-group
		= f.input :name, label: false, input_html: { class: "form-control", placeholder: 'Nombre' }
		%span.input-group-btn
			= link_to_remove_association f, class: "btn btn-warning", style: "color:white;" do
				%i.fa.fa-trash
	%br/

app/views/inyx_blog_rails/categories/_view_lg_md.html.haml
%div{'ng-init'=>"init(#{@objects.to_json}, '/admin/posts/categories', '#{params[:search]}', #{@total_rows}, #{Kaminari.config.default_per_page})", "resize" => ""}
  .grid-content
    .col-lg-9.col-md-9{ style: "padding:0px;" }
      .list-wrapper
        .panel.panel-default
          - flash.each do |name, msg|
            - if msg.is_a?(String)
              %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'} pull-right", id: "message_alerts"}
                %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
                = content_tag :div, msg, :id => "flash_#{name}"
          .panel-heading#list-heading
            - if can? :new, InyxBlogRails::Category
              = link_to new_category_path, class: "btn btn-default btn-action", title: t("admin.buttons.new") do
                %i.fa.fa-plus-circle
            %a.btn.btn-default.btn-action{"ng-click" => "refresh()", "ng-disabled" => "pagesItemsSelected[currentPageServer].length != 0", :title => t("admin.buttons.refresh") }
              %i.fa.fa-refresh#icon-refresh{'ng-show'=>"!loadingRefresh"}
              %i.fa.fa-refresh.fa-spin{'ng-show'=>"loadingRefresh"}
            - if can? :delete, InyxBlogRails::Category
              %a.btn.btn-default.btn-action{"ng-show" => "objects.length", "ng-click" => "allSelected(objects)", :title => t("admin.buttons.select_all") }
                %i.fa.fa-square-o{"ng-show" => "!btnDelete"}
                %i.fa.fa-check-square-o{ "ng-show" => "btnDelete" } 
              %a.btn.btn-default.btn-action#btn-delete{ "ng-show" => "btnDelete", "ng-click" => "destroy('¿Estas seguro de querer eliminar las categorías seleccionadas?, esta acción eliminará todo los posts pertenecientes a ella.')", :title => t("admin.buttons.trash") }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingDelete" }
                %i.fa.fa-trash-o{ 'ng-show' => "!loadingDelete" }
            .paginator.pull-right{ "ng-show" => "objects.length > 0"}
              %button.btn.btn-default.pull-right.hidden-xs{'disabled'=>"", style:"color:#000; margin-left:3px;"}
                Página {{currentPage+1}} de {{numberOfPages()}}
              %a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
                %i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
              %a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
                %i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
                %i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
          .panel-body
            #table-scroll
              %table.grid{style: "width:100%"}
                %tbody
                  %tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize" }
                    - if can? :delete, InyxBlogRails::Category
                      %td{ width: "1px;" }
                        .checkboxFour
                          %input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
                          %label{ for: "check-{{object.id}}" }
                            %span
                    %td {{object.name}}

    .col-lg-3.col-md-3{ style: "padding:0px;"}
      .show-wrapper
        .show-head
        .show-body
          .panel.panel-default
            .panel-heading{ style: "height:55px;" }
              .actions{ "ng-show" => "object_data" }
                .title.pull-left{ style: "margin-top:6px;" }
                  %i.fa.fa-tags
                  Categoría - {{ object_data.id }}
                - if can? :destroy, InyxBlogRails::Category
                  = link_to "{{destroy_path(object_data.id)}}", title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar esta categoría?, esta acción eliminara todo los posts pertenecientes a ella.' }, class: "btn btn-default btn-action pull-right", "ng-show" => "object_data" do
                    %i.fa.fa-remove
                - if can? :edit, InyxBlogRails::Category
                  = link_to "{{edit_path(object_data.id)}}", title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", "ng-show" => "object_data", style: "margin-right:3px;" do
                    %i.fa.fa-pencil
              .no-actions{ "ng-show" => "!object_data", style: "margin-top:6px;" }
                %i.fa.fa-tag
                Categoría
            .panel-body
              .data{ style: "height: {{windowHeight-104}}px;" }
                %img{ "ng-show" => "object_data.image", "ng-src" => "{{object_data.image}}", alt: "{{posts.title}}", title: "{{posts.title}}" }
                .attributes{ "ng-show" => "object_data" }
                  %label Nombre: 
                  {{object_data.name}}
                  %br/
                  %label Subcategorías: 
                  {{object_data.subcategories | titlecase }}
                  %br/
                .no-data{ "ng-show" => "!object_data"}
                  %center
                    No se ha seleccionado una categoría para mostrar.
        .show-footer

app/views/inyx_blog_rails/categories/_view_sm_xs.html.haml
= link_to new_category_path, class: "float-button" do
	%i.fa.fa-plus
.panel.panel-default{style:"margin-top:50px"}
	.panel-header
		.paginator{ "ng-show" => "objects.length > 0"}
			%center
				Página {{currentPage+1}} de {{numberOfPages()}}
			%a.btn.btn-default.pull-right.next{ "ng-disabled"=>"currentPage >= total_objects/pageSize - 1 || loadingNext", "ng-click"=>"next()", style: "margin-left:3px" }
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingNext" }
				%i.fa.fa-arrow-right{ 'ng-show' => "!loadingNext" }
			%a.btn.btn-default.pull-right.last{'ng-disabled'=>"currentPage == 0 || loadingLast", "ng-click"=>"last()"}
				%i.fa.fa-circle-o-notch.fa-spin{ 'ng-show' => "loadingLast" }
				%i.fa.fa-arrow-left{ 'ng-show' => "!loadingLast" }
	.panel-body#grid{ style: "border-right: 1px solid #e7e7e7;padding-left: 0px;padding-right: 0px;border-top-width: 36px;" }	
		%table.grid{style: "width:100%;"}
			%tbody
				%tr{ class: "select-{{object.checked}}", "ng-click" => "show_object(object)", :id => "row-{{object.id}}", "ng-repeat" => "object in objects | startFrom:currentPage*pageSize | limitTo:pageSize"}
					%td{ width: "1px;" }
						.checkboxFour
							%input.checkboxFourInput{:id => "check-{{object.id}}", :type => "checkbox", "ng-model" => "object.checked", "ng-click" => "selected(object); $event.stopPorpagation();" }
							%label{ for: "check-{{object.id}}" }
								%span
					%td
						= link_to "{{show_path(object.id)}}", style: "width:100%;" do
							{{ object.name | titlecase }}
				%tr{"ng-show" => "!objects.length"}
					%td{:style => "width:100%"}
						%center
							%i.fa.fa-frown-o
							No hay categorías.

app/views/inyx_blog_rails/categories/edit.html.haml
= content_for(:title, "Admin - Categoría de Post | Editar")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_blog_rails/categories/index.html.haml
= content_for(:title, "Admin - Post - Categorías")

.view-lg-md.hidden-xs.hidden-sm
  = render "view_lg_md"
.view-sm-xs.hidden-lg.hidden-md
  = render "view_sm_xs"

app/views/inyx_blog_rails/categories/new.html.haml
= content_for(:title, "Admin - Categoría de Post | Nuevo")
%div{ style: "padding:10px; padding-bottom:0px;"}
	= render 'form'

app/views/inyx_blog_rails/categories/show.html.haml
= content_for(:title, "Admin - Post | #{@category.name}")
%div
	= render "layouts/admin/messages"
	.panel.panel-default{style:"margin-top:50px"}
		.panel-heading#heading-show{ style: "padding-top:5px;"}
			.actions
				.title.pull-left{ style: "margin-top:8px;" }
					%i.fa.fa-tags
					Categoría - 
					= @category.id
				= link_to category_path(@category), title: t('admin.actions.delete'), :method => :delete, :data => { :confirm => '¿Estas seguro de querer eliminar este usuario?' }, class: "btn btn-default btn-action pull-right" do
					%i.fa.fa-remove
				= link_to edit_category_path(@category), title: t('admin.actions.edit'), class: "btn btn-default btn-action pull-right", style: "margin-right:3px;" do
					%i.fa.fa-pencil
	.panel-body#body-show
		%label Nombre:
		= @category.name
		%br/
		%label Subcategorías:
		= @category.subcategories.map { |sub| sub.name }.join(", ")
		%br/